### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ZeroDevNull** [Shoobx/xmldiff#125]
OS: Ubuntu 20.04
XMLDIFF version: 2.4/2.6.3

When I diff these two files I get the following error:

```
Traceback (most recent call last):
  File "/data/usr/bin/xmlpatch", line 11, in <module>
    load_entry_point('xmldiff==2.4', 'console_scripts', 'xmlpatch')()
  File "/data/usr/lib/python3/dist-packages/xmldiff/main.py", line 171, in patch_command
    result = patch_file(args.patchfile, args.xmlfile)
  File "/data/usr/lib/python3/dist-packages/xmldiff/main.py", line 148, in patch_file
    tree = patch_tree(actions, tree)
  File "/data/usr/lib/python3/dist-packages/xmldiff/main.py", line 124, in patch_tree
    return patcher.patch(actions, tree)
  File "/data/usr/lib/python3/dist-packages/xmldiff/patch.py", line 15, in patch
    self.handle_action(action, result)
  File "/data/usr/lib/python3/dist-packages/xmldiff/patch.py", line 22, in handle_action
    method(action, tree)
  File "/data/usr/lib/python3/dist-packages/xmldiff/patch.py", line 34, in _handle_RenameNode
    tree.xpath(action.node)[0].tag = action.tag
IndexError: list index out of range
```

The commands I run are:
xmldiff cfgspawnabletypes1.xml cfgspawnabletypes2.xml > cfgspawnabletypes.diff
xmlpatch cfgspawnabletypes.diff cfgspawnabletypes1.xml

The exact files used:
[xmltest.zip](https://github.com/Shoobx/xmldiff/files/13324473/xmltest.zip)

I've tried to remove all whitepaces and comments but that didn't work.

**Comment by regebro** [comment]
Well, this is a bug, but these files are huge, and almost every single item has changed, so it's practically impossible to debug this. There are 550 actions before the one that fails, and to figure out why this one fails, I would have to step through all of them and see how they affect the state of the tree to figure out what goes wrong, because it's somewhere in the preceding 550 actions.

If you can make a smaller case with a similar error that could be helpful.

Also, the diffs are larger than the original file, so I'm not sure what the purpose of diffing and patching is in this case.

**Comment by Ymil** [comment]
Hello, I have a similar problem, this is my error message, is it equivalent?

```
  File "/venv/lib/python3.8/site-packages/xmldiff/main.py", line 50, in diff_files
    return _diff(etree.parse, left, right,
  File "/venv/lib/python3.8/site-packages/xmldiff/main.py", line 38, in _diff
    return diff_trees(left_tree, right_tree, diff_options=diff_options,
  File "/venv/lib/python3.8/site-packages/xmldiff/main.py", line 30, in diff_trees
    return formatter.format(diffs, left)
  File "/venv/lib/python3.8/site-packages/xmldiff/formatting.py", line 717, in format
    actions.extend(self.handle_action(action, orig_tree))
  File "/venv/lib/python3.8/site-packages/xmldiff/formatting.py", line 727, in handle_action
    for item in method(action, orig_tree):
  File "/venv/lib/python3.8/site-packages/xmldiff/formatting.py", line 758, in _handle_MoveNode
    node = orig_tree.xpath(action.node)[0]
IndexError: list index out of range
```

I added the following code for a more user-friendly message, perhaps this can be added to the library code:
```python
        except IndexError as e:
            if str(e) == "list index out of range":
                diffs.append("Too many changes to compare, check manually.")            
            else:
                raise IndexError(e)

**Comment by regebro** [comment]
No, but it may be related. Again, if someone could make a smaller example where this happens I should have time to look at it.

**Comment by thomas-bc** [comment]
@regebro I am unsure that this is related, but I believe it might.

<details><summary>Click to expand example XMLs</summary>
<p>

`left.xml`:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<items>
    <item_defs>
        <item version="1.1.0" my_id="0001">
            <subitem></subitem>
            <olditem></olditem>
        </item>
        <item version="1.5.0" my_id="0002">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0003">
            <subitem></subitem>
        </item>
    </item_defs>
</items>

````

`right.xml`:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<items>
    <item_defs>
        <item version="1.1.0" my_id="0001">
            <subitem></subitem>
        </item>
        <item version="1.5.0" my_id="0002">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0003">
            <subitem></subitem>
        </item>
    </item_defs>
</items>
```

</p>
</details> 

I am using `uniqueattrs=['my_id']`

This yields the following result for me
```
[move, /items/item_defs/item[1]/olditem[1], /items/item_defs/item[2], 0]
[rename, /items/item_defs/item[2]/olditem[1], subitem]
[move, /items/item_defs/item[2]/subitem[2], /items/item_defs/item[3], 0]
[delete, /items/item_defs/item[3]/subitem[2]]
```

In reality, all this is doing is deleting the `<olditem>` node. But somehow it is being moved around all the way down before being deleted.

Notice that when adding more <items> (see longer example below), the node does in fact try to move "all the way down" in the list...

<details><summary>Click to expand longer example</summary>
<p>

`left.xml`:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<items>
    <item_defs>
        <item version="1.1.0" my_id="0001">
            <subitem></subitem>
            <olditem></olditem>
        </item>
        <item version="1.5.0" my_id="0002">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0003">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0004">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0005">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0006">
            <subitem></subitem>
        </item>
    </item_defs>
</items>

````

</p>
</details> 


This is a dummy example but the same kind of issue was happening on a real-life example of mine.

**Comment by thomas-bc** [comment]
I also noticed that renaming `olditem` to a very different name resolves the erroneous RenameAction and the issue disappears.

Now I have a very weird example

<details><summary>Click to expand longer example</summary>
<p>

`left.xml`:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<items>
    <item_defs>
        <item version="1.1.0" my_id="0001">
            <olditem></olditem>
            <subitem></subitem>
        </item>
        <item version="1.5.0" my_id="0002">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0003">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0004">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0005">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0006">
            <subitem></subitem>
        </item>
    </item_defs>
</items>

````

`right.xml`:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<items>
    <item_defs>
        <item version="1.1.0" my_id="0001">
            <subitem></subitem>
        </item>
        <item version="1.5.0" my_id="0002">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0003">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0004">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0005">
            <subitem></subitem>
        </item>
        <item version="2.0.0" my_id="0003">
            <subitem></subitem>
        </item>
    </item_defs>
</items>

```
</p>
</details> 

Gives me (still using `my_id` as unique ID)
```
[insert, /items/item_defs[1], item, 5]
[insert-attribute, /items/item_defs/item[6], my_id, "0003"]
[insert-attribute, /items/item_defs/item[6], version, "2.0.0"]
[rename, /items/item_defs/item[1]/olditem[1], subitem]
[move, /items/item_defs/item[1]/subitem[2], /items/item_defs/item[2], 0]
[move, /items/item_defs/item[2]/subitem[2], /items/item_defs/item[3], 0]
[move, /items/item_defs/item[3]/subitem[2], /items/item_defs/item[4], 0]
[move, /items/item_defs/item[4]/subitem[2], /items/item_defs/item[5], 0]
[move, /items/item_defs/item[5]/subitem[2], /items/item_defs/item[6], 0]
[delete, /items/item_defs/item[7]/subitem[1]]
[delete, /items/item_defs/item[7]]
```

It's doing a lot of things, including messing around with things that are uniquely identified, when only one node is deleted...
Could there be a bug in the algorithm there?
